checkpoints:
  checkpoint_interval: 50000
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  # resume_checkpoint_path: checkpoints
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_overwrite_cache: false
      dataset_processing_num_proc_per_process: 1
      hf_dataset_config_name: null
      hf_dataset_or_datasets: roneneldan/TinyStories
      hf_dataset_splits: train
      text_column_name: text
    num_loading_workers: 1
    seed: 42
  name: Stable Training Stage
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: fp8_for_nanotron
  run: exp40_50m_5k_warmup_and_update_clipping_and_0.2_weight_decay_and_512_batch_size_without_grad_clipping_with_layerscale_zeroinit_and_beta2_0.93_and_lr_0.0003
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
  monitor_model_states: true
  monitor_model_states_using_hooks: true
model:
  ddp_bucket_cap_mb: 25
  dtype: float8
  init_method:
    # std: 0.25 # sqrt(1/16)
    # std: 0.125 # sqrt(1/64)
    std: 0.04419417382415922 # sqrt(1/512)
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    # hidden_act: silu
    hidden_act: gelu
    hidden_size: 512
    initializer_range: 0.02
    intermediate_size: 2048
    is_llama_config: true
    max_position_embeddings: 128
    num_attention_heads: 16
    num_hidden_layers: 2
    num_key_value_heads: 16
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 49152
# optimizer:
#   accumulate_grad_in_fp32: false
#   clip_grad: 1.0
#   # learning_rate_scheduler:
#   #   learning_rate: 0.01
#   #   lr_decay_starting_step: null
#   #   lr_decay_steps: 13
#   #   lr_decay_style: linear
#   #   lr_warmup_steps: 2
#   #   lr_warmup_style: constant
#   #   min_decay_lr: 1.0e-05

#   # learning_rate_scheduler:
#   #   learning_rate: 0.00015
#   #   lr_decay_starting_step: null
#   #   # lr_decay_steps: null
#   #   lr_decay_style: linear
#   #   lr_warmup_steps: 60
#   #   lr_warmup_style: constant
#   #   min_decay_lr: 1.0e-05

#   optimizer_factory:
#     adam_beta1: 0.9
#     adam_beta2: 0.999
#     adam_eps: 1.0e-08
#     name: adam
#     torch_adam_is_fused: true
#   weight_decay: 0.1
#   zero_stage: 0


optimizer:
  accumulate_grad_in_fp32: false
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 5000 # 10% warm up of total training steps
    lr_warmup_style: linear
    min_decay_lr: 0.00003

  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.93
    adam_eps: 1.0e-08
    name: custom_fp8_adam
    torch_adam_is_fused: true
  weight_decay: 0.2
  zero_stage: 0
  # clip_grad: 1.0
  update_clipping: true

parallelism:
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  # tp_linear_async_communication: true
  # tp_mode: REDUCE_SCATTER

  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null
tokens:
  # NOTE: micro_batch_size * sequence_length * batch_accumulation_per_replica
  # = 128 * 256 * 1 = 16384
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 512 # 256
  sequence_length: 128
  train_steps: 24376
  val_check_interval: -1

fp8:
  resid_dtype: float32
  accum_dtype: bfloat16
  optim:
    master_weight_dtype: float32
    accum_dtype: float32
    exp_avg_dtype: float32
    exp_avg_sq_dtype: float32

  clipped_softmax: true
  clipped_softmax_zeta: 1.3
  clipped_softmax_gamma: -0.03

  layer_scale: true
  layer_scale_init: zeros
